colorScheme = "hearc"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true

[header]
layout = "fixed-fill-blur"

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = false
showScrollToTop = true

[homepage]
layout = "page" # page / profile
homepageImage = "image.jpg"
showRecent = false
showRecentItems = 12
showMoreLink = true
showMoreLinkDest = "/projects"
cardView = true
cardViewScreenWidth = true
layoutBackgroundBlur = true

[article]
showDate = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "basic"
showBreadcrumbs = false
showDraftLabel = false
showEdit = false
editURL = "https://github.com/username/repo/"
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = true
showReadingTime = false
showTableOfContents = false
showTaxonomies = true
showAuthorsBadges = true
showWordCount = false
showSummary = false

[list]
showHero = false
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showTableOfContents = true
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = true

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[term]
cardView = true
cardViewScreenWidth = false
groupByYear = true

[firebase]

[fathomAnalytics]

[verification]
